export default {
    tipo_movimiento_id : '',
    persona_marcacion : {
        'personal_id' : '',
        'nombre_completo'  : '',
        'fecha_hora' : '',
        'tipo_marcacion_id' : '',
        'imagen_url' : '',
        'tipo_movimiento_id' : '',
    },
    personal_marcacion : [],
    obtener_personal_url : `https://apigateway.zamine-temp.com/api/v1/checkpoint/get-personal`,
    guardar_personal_marcacion_url : `https://apigateway.zamine-temp.com/api/v1/checkpoint/store`,
    obtener_marcacion_persona_logueada_url : `https://apigateway.zamine-temp.com/api/v1/checkpoint/list-my-assists`,
    personal_marcacion_logueado_cabecera : {
        'total'         : '',
        'per_page'      : '',
        'current_page'  : '',
        'last_page'     : '',
        'next_page_url' : '',
        'prev_page_url' : '',
        'from'          : '',
        'to'            : '',
    },
    personal_marcacion_logueado : [],
    obtener_marcacion_personal_diario : `https://apigateway.zamine-temp.com/api/v1/checkpoint/list-personal-current-day`,
    personal_marcacion_diario_cabecera : {
        'total'         : '',
        'per_page'      : '',
        'current_page'  : '',
        'last_page'     : '',
        'next_page_url' : '',
        'prev_page_url' : '',
        'from'          : '',
        'to'            : '',
    },
    personal_marcacion_diario : [],
    obtener_marcacion_personal_historial : `https://apigateway.zamine-temp.com/api/v1/checkpoint/list-personal-history-assistance`,
    personal_marcacion_historial_cabecera : {
        'total'         : '',
        'per_page'      : '',
        'current_page'  : '',
        'last_page'     : '',
        'next_page_url' : '',
        'prev_page_url' : '',
        'from'          : '',
        'to'            : '',
    },
    personal_marcacion_historial : [],
}